#!/usr/bin/env node

const { exec } = require("child_process");
const { writeFile } = require("fs");

const bash = (command = 'echo "Hello world"') => {
  return new Promise((resolve, reject) => {
    exec(command, (error, stdout, stderr) => {
      if (error) {
        reject(error);
        return;
      }
      if (stderr) {
        reject(new Error(stderr));
        return;
      }
      resolve(stdout);
    });
  });
};

const importFile = async () => {
  try {
    const localParams = await import("/tmp/parameters.js");
    return localParams.parameterStore;
  } catch {
    return {};
  }
};
(async function () {
  await bash("tsc ./lib/common/parameters.ts --outDir /tmp --skipLibCheck");
  const paramStore = await importFile();
  const parameters = JSON.stringify(paramStore, null, 2);

  writeFile('/tmp/parameters.json', parameters, (err) => {
    if (err){
      console.log("Something went wrong", err);
      return 
    }
    
    console.log("Json created successfully 🎉")
  })
})();
