#!/bin/sh
echo "Connection management deployment"
set -e

export CDK_DEPLOY_ENV='fds'
export CDK_DEPLOY_REGION='ca-central-1'
export CDK_ORG_ID="o-f59lxev2zf"
export CDK_PIPELINE_ACCOUNT='988262432034' # telus-ci-cd-global-iot
export CDK_DATA_ACCOUNT='857430176134' # platform-sh-iot-services-sandbox-data
export CDK_API_ACCOUNT='445087146553' # platform-sh-iot-services-sandbox-api
export CDK_SERVICE_A_ACCOUNT='231154069617' # platform-sh-iot-services-sandbox-a
export CDK_SERVICE_B_ACCOUNT='021859354158' # platform-sh-iot-services-sandbox-b
export CDK_SERVICE_ACCOUNT=$CDK_SERVICE_A_ACCOUNT
export CDK_DEPLOY_TENANT="telus" # updated from "telus" on 12/20/23
export CDK_DEPLOY_BUSINESS_UNIT="sh"
export CDK_DEPLOY_COLOR="blue"
export CDK_ACTIVE_COLOR="blue"
export CDK_QUALIFIER="hnb659fds"
export AWS_PROFILE="telus-ci-cd"
export AWS_REGION="ca-central-1"
export TENANT_NAME=telus
export BUSINESS_UNIT=sh
export CDK_DEPLOY_AGE=deploymentIdLatest
export SEARCH_SERVICE_REGION=ca-central-1
export CDK_DEPLOY_OWNER=$CDK_DEPLOY_ENV # TODO: remove
export STACK_SUFFIX=$CDK_DEPLOY_ENV # TODO: remove
export MEMBER_IDP_CLIENT_SECRET="53dd15b2-adc6-45cf-8ba6-8c07102ed63a"
export TENANT_IDP_CLIENT_SECRET="53dd15b2-adc6-45cf-8ba6-8c07102ed63a"
export OPENSEARCH_VPC=vpc-08b9416fc6a2d9bd0
export OPENSEARCH_SUBNET=subnet-0a2f0a0592b89c5fb,subnet-039b445f7a7deddeb
export OPENSEARCH_VPC_OWNERID=763524190213
export AWS_PROFILE=sh-cicd-global-iot-988262432034

if [ -z "$AWS_ACCESS_KEY_ID" ]; then
  echo -e "\e[31m💀 ***Please paste Telus-iot-Developer (account 380625108321) access keys*** 💀\e[0m"
  exit 1
fi

if [ -z "$MEMBER_IDP_CLIENT_SECRET " ]; then
  echo -e "\e[31m💀 ***Please paste MEMBER_IDP_CLIENT_SECRET *** 💀\e[0m"
  exit 1
fi

if [ -z "$TENANT_IDP_CLIENT_SECRET " ]; then
  echo -e "\e[31m💀 ***Please paste TENANT_IDP_CLIENT_SECRET *** 💀\e[0m"
  exit 1
fi

if ! aws sts get-caller-identity >/dev/null 2>&1; then
  aws sso login --profile sh-cicd-global-iot-988262432034
fi


echo -e "\e[1;93m"
echo "╔══════════════════════════════════════════════════╗"
echo "║      🚀 AUTHORIZATION MANAGEMENT DEPLOYMENT 🚀   ║"
echo "╚══════════════════════════════════════════════════╝"
echo -e "\e[0m"

cd platform/apps/

sudo find . -maxdepth 1 -type d -name "scripts" -exec chmod +x {} \;

cd authorization-management 
./scripts/deploy.sh dev deploy
cd ..

echo -e "\e[1;93m"
echo "╔══════════════════════════════════════════════════╗"
echo "║         🚀 API GATEWAY DEPLOYMENT 🚀             ║"
echo "╚══════════════════════════════════════════════════╝"
echo -e "\e[0m"

cd unified-api-gateway
./scripts/deploy.sh dev deploy
cd ..

echo -e "\e[1;93m"
echo "╔══════════════════════════════════════════════════╗"
echo "║      🚀 AUTHENTICATION MANAGER DEPLOYMENT 🚀     ║"
echo "╚══════════════════════════════════════════════════╝"
echo -e "\e[0m"

cd authentication-management
node ./scripts/proto-gen.cjs
sh ./scripts/create-ssm-params.sh || true
./scripts/deploy.sh dev deploy || true
cd ..

echo -e "\e[1;93m"
echo "╔══════════════════════════════════════════════════╗"
echo "║    🚀 CONNECTION MANAGEMENT DEPLOYMENT 🚀        ║"
echo "╚══════════════════════════════════════════════════╝"
echo -e "\e[0m"


cd connection-management
./scripts/deploy.sh data deploy
./scripts/deploy.sh svc-a deploy
./scripts/deploy.sh api deploy
