#!/bin/bash

bash() {
  command=$1
  eval $command
  returnCode=$?

  if [ $returnCode -ne 0 ]; then
    echo "Error executing: $command"
    exit 1
  fi  
}

actual_branch=$(git branch --show-current)
echo "$actual_branch"

bash "git checkout master"

bash "git fetch"

bash "git pull"

bash "git checkout $actual_branch"
bash "git merge master"
